predict:
  SEED: 10
  comments:
    YOUTUBE_API_KEY: AIzaSyDPNDTO39cSdmOs2tVdNRQ9B0SSoOn3UX0
    count_video: 100
    limit: 30
    maxResults: 100
    nextPageToken: ''
    query: хуй войне
  dir_folder: .
  model_lr: LogisticRegression
  model_vec: vector_tfidf
  name_file: data/text.csv
  num_top: 10
  stopwords: russian
  version_lr: 4
  version_vec: 4
train:
  SEED: 10
  clustering:
    affinity: cosine
    count_max_clusters: 15
    silhouette_metric: euclidean
  comments:
    YOUTUBE_API_KEY: AIzaSyDPNDTO39cSdmOs2tVdNRQ9B0SSoOn3UX0
    count_video: 1500
    limit: 100
    maxResults: 300
    nextPageToken: ''
    query: хуй войне
  cross_val:
    test_size: 0.3
  dir_folder: .
  model:
    class_weight: balanced
  model_lr: LogisticRegression
  model_vec: vector_tfidf
  name_experiment: hv-1
  stopwords: russian
  tf_model:
    max_features: 500
